<?php

namespace Database\Seeders;

use App\Models\Dish;
use Illuminate\Database\Seeder;

class DishSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        Dish::insert([
            // =============================================
            // AGUACHILE (category_id: 1) - 450g y 220g
            // =============================================

            // Celestino's
            [
                'id' => 1,
                'category_id' => 1,
                'name' => "Aguachile Celestino's 450g",
                'description' => 'Camarón enchilado, camarón cocido y pulpo en salsa de la casa acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 114.00,
                'sale_price' => 285.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => "Aguachile Celestino's 220g",
                'description' => 'Camarón enchilado, camarón cocido y pulpo en salsa de la casa acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 74.00,
                'sale_price' => 185.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // De la 'R'
            [
                'id' => 3,
                'category_id' => 1,
                'name' => "Aguachile De la 'R' 450g",
                'description' => 'Tentáculo de pulpo en combinación de camarón curtido en jugo de limón y capa de serrano laminado, acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 106.00,
                'sale_price' => 265.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'name' => "Aguachile De la 'R' 220g",
                'description' => 'Tentáculo de pulpo en combinación de camarón curtido en jugo de limón y capa de serrano laminado, acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 66.00,
                'sale_price' => 165.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mixto
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Aguachile Mixto 450g',
                'description' => 'El "tradicional" combinado con camarón cocido.',
                'cost_price' => 106.00,
                'sale_price' => 265.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'Aguachile Mixto 220g',
                'description' => 'El "tradicional" combinado con camarón cocido.',
                'cost_price' => 66.00,
                'sale_price' => 165.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // El Maviri
            [
                'id' => 7,
                'category_id' => 1,
                'name' => 'Aguachile El Maviri 450g',
                'description' => 'Callo de róbalo, pulpo y camarón curtido en salsa de la casa con una cama de pepino y cebolla.',
                'cost_price' => 106.00,
                'sale_price' => 265.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'category_id' => 1,
                'name' => 'Aguachile El Maviri 220g',
                'description' => 'Callo de róbalo, pulpo y camarón curtido en salsa de la casa con una cama de pepino y cebolla.',
                'cost_price' => 66.00,
                'sale_price' => 165.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Tradicional
            [
                'id' => 9,
                'category_id' => 1,
                'name' => 'Aguachile Tradicional 450g',
                'description' => 'Camarón enchilado previamente curtido en jugo de limón con un toque de chile chiltepin y sal de mar acompañado con pepino y cebolla.',
                'cost_price' => 108.00,
                'sale_price' => 270.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'name' => 'Aguachile Tradicional 220g',
                'description' => 'Camarón enchilado previamente curtido en jugo de limón con un toque de chile chiltepin y sal de mar acompañado con pepino y cebolla.',
                'cost_price' => 68.00,
                'sale_price' => 170.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Patasalada
            [
                'id' => 11,
                'category_id' => 1,
                'name' => 'Aguachile Patasalada 450g',
                'description' => 'Combinación de atún, camarón cocido, camarón curtido en jugo de limón con cama de pepino y cebolla.',
                'cost_price' => 110.00,
                'sale_price' => 275.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'category_id' => 1,
                'name' => 'Aguachile Patasalada 220g',
                'description' => 'Combinación de atún, camarón cocido, camarón curtido en jugo de limón con cama de pepino y cebolla.',
                'cost_price' => 70.00,
                'sale_price' => 175.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Del Pacífico
            [
                'id' => 13,
                'category_id' => 1,
                'name' => 'Aguachile Del Pacífico 450g',
                'description' => 'Callo de róbalo, atún y pulpo en salsa negra acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 102.00,
                'sale_price' => 255.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'category_id' => 1,
                'name' => 'Aguachile Del Pacífico 220g',
                'description' => 'Callo de róbalo, atún y pulpo en salsa negra acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 62.00,
                'sale_price' => 155.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Tarrallazo
            [
                'id' => 15,
                'category_id' => 1,
                'name' => 'Aguachile Tarrallazo 450g',
                'description' => '3 proteínas a elegir (camarón enchilado, camarón cocido, pulpo, atún o callo de róbalo) en salsa de la casa acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 114.00,
                'sale_price' => 285.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'category_id' => 1,
                'name' => 'Aguachile Tarrallazo 220g',
                'description' => '3 proteínas a elegir (camarón enchilado, camarón cocido, pulpo, atún o callo de róbalo) en salsa de la casa acompañado con pepino y cebolla cortado en julianas.',
                'cost_price' => 74.00,
                'sale_price' => 185.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =============================================
            // CEVICHE (category_id: 2) - 450g y 220g
            // =============================================

            // Sinaloense
            [
                'id' => 17,
                'category_id' => 2,
                'name' => 'Ceviche Sinaloense 450g',
                'description' => 'Camarón curtido, camarón cocido y pulpo mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 98.00,
                'sale_price' => 245.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'category_id' => 2,
                'name' => 'Ceviche Sinaloense 220g',
                'description' => 'Camarón curtido, camarón cocido y pulpo mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 58.00,
                'sale_price' => 145.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Culichi
            [
                'id' => 19,
                'category_id' => 2,
                'name' => 'Ceviche Culichi 450g',
                'description' => 'Camarón cocido, callo de róbalo y pulpo mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 98.00,
                'sale_price' => 245.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'category_id' => 2,
                'name' => 'Ceviche Culichi 220g',
                'description' => 'Camarón cocido, callo de róbalo y pulpo mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 58.00,
                'sale_price' => 145.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Altata
            [
                'id' => 21,
                'category_id' => 2,
                'name' => 'Ceviche Altata 450g',
                'description' => 'Callo de Róbalo mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 92.00,
                'sale_price' => 230.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'category_id' => 2,
                'name' => 'Ceviche Altata 220g',
                'description' => 'Callo de Róbalo mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 52.00,
                'sale_price' => 130.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mixto
            [
                'id' => 23,
                'category_id' => 2,
                'name' => 'Ceviche Mixto 450g',
                'description' => 'Camarón curtido y camarón cocido mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 92.00,
                'sale_price' => 230.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'category_id' => 2,
                'name' => 'Ceviche Mixto 220g',
                'description' => 'Camarón curtido y camarón cocido mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 52.00,
                'sale_price' => 130.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Tradicional
            [
                'id' => 25,
                'category_id' => 2,
                'name' => 'Ceviche Tradicional 450g',
                'description' => 'Camarón enchilado mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 96.00,
                'sale_price' => 240.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'category_id' => 2,
                'name' => 'Ceviche Tradicional 220g',
                'description' => 'Camarón enchilado mezclados con Kermato, pepino, tomate y cebolla cortados finamente.',
                'cost_price' => 56.00,
                'sale_price' => 140.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =============================================
            // TAQUERÍA DEL PACÍFICO (category_id: 3)
            // =============================================
            [
                'id' => 27,
                'category_id' => 3,
                'name' => 'Taco Gobernador',
                'description' => 'La creación más famosa de los mariscos culichis, un taco a base de guisado de camarón con queso.',
                'cost_price' => 24.00,
                'sale_price' => 60.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'category_id' => 3,
                'name' => 'Mazatlecos',
                'description' => '3 tacos de marlin sobre tortilla de maíz con una costra de queso tipo gouda.',
                'cost_price' => 70.00,
                'sale_price' => 175.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'category_id' => 3,
                'name' => 'Reformeños',
                'description' => 'Orden de 3 tacos de pescado capeado servido en tortilla de maíz, desde la Reforma Angostura.',
                'cost_price' => 54.00,
                'sale_price' => 135.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'category_id' => 3,
                'name' => 'Costeños',
                'description' => 'Orden de 3 tacos de camarones capeados cubiertos con una capa ligera y crujiente.',
                'cost_price' => 66.00,
                'sale_price' => 165.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'category_id' => 3,
                'name' => 'Las de Harina',
                'description' => '1 taco costeño o mazatleco hecho quesadilla en tortilla de harina gratinada con queso tipo gouda.',
                'cost_price' => 28.00,
                'sale_price' => 70.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =============================================
            // ESPECIALES (category_id: 4)
            // =============================================
            [
                'id' => 32,
                'category_id' => 4,
                'name' => 'Es Queen Apa!',
                'description' => 'De Escuinapa para el mundo, camarones zarandeados con exquisito adobo de la casa.',
                'cost_price' => 78.00,
                'sale_price' => 195.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'category_id' => 4,
                'name' => 'El Rey del Pacífico',
                'description' => 'Una combinación digna de reyes entre pulpo, camarón cocido, atún, camarón curtido, acompañado de bastones de pepino y cebollas en juliana y callo de hacha que corona este manjar para reyes y reinas.',
                'cost_price' => 476.00,
                'sale_price' => 1190.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'category_id' => 4,
                'name' => 'Zarandeado del Rey',
                'description' => 'Un pescado zarandeado traído desde nuestras costas sinaloenses, coronado con camarones salteados en mantequilla. Por kilo, solo domingo.',
                'cost_price' => 192.00,
                'sale_price' => 480.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'category_id' => 4,
                'name' => 'Camarones Roca',
                'description' => 'Camarones estilo tempura aderezados con salsa oriental y un toque de Sriracha.',
                'cost_price' => 88.00,
                'sale_price' => 220.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =============================================
            // POSTRES (category_id: 5)
            // =============================================
            [
                'id' => 36,
                'category_id' => 5,
                'name' => 'Churros',
                'description' => null,
                'cost_price' => 25.00,
                'sale_price' => 62.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'category_id' => 5,
                'name' => 'Flan',
                'description' => null,
                'cost_price' => 30.00,
                'sale_price' => 75.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'category_id' => 5,
                'name' => 'Sandwich de Churro',
                'description' => null,
                'cost_price' => 28.00,
                'sale_price' => 69.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'category_id' => 5,
                'name' => 'Choco Fudge',
                'description' => null,
                'cost_price' => 32.00,
                'sale_price' => 80.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'category_id' => 5,
                'name' => 'Bola de Nieve (extra)',
                'description' => 'Añade una bola de nieve a tu postre.',
                'cost_price' => 14.00,
                'sale_price' => 35.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =============================================
            // BEBIDAS (category_id: 6)
            // =============================================
            [
                'id' => 41,
                'category_id' => 6,
                'name' => 'Agua Natural: Jamaica, Limonada',
                'description' => null,
                'cost_price' => 8.00,
                'sale_price' => 20.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'category_id' => 6,
                'name' => 'Agua Natural',
                'description' => null,
                'cost_price' => 8.00,
                'sale_price' => 20.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'category_id' => 6,
                'name' => 'Topo Chico',
                'description' => null,
                'cost_price' => 18.00,
                'sale_price' => 45.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'category_id' => 6,
                'name' => 'Perrier',
                'description' => null,
                'cost_price' => 24.00,
                'sale_price' => 60.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'category_id' => 6,
                'name' => 'Productos Coca Cola',
                'description' => null,
                'cost_price' => 18.00,
                'sale_price' => 45.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'category_id' => 6,
                'name' => 'Cerveza: Amstel, XX Lager',
                'description' => null,
                'cost_price' => 18.00,
                'sale_price' => 45.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'category_id' => 6,
                'name' => 'Cerveza: Modelo Especial, Pacífico Suave, Pacífico Clara',
                'description' => null,
                'cost_price' => 18.00,
                'sale_price' => 45.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'category_id' => 6,
                'name' => 'Cerveza: Corona, Victoria',
                'description' => null,
                'cost_price' => 16.00,
                'sale_price' => 40.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =============================================
            // NIÑOS (category_id: 7)
            // =============================================
            [
                'id' => 49,
                'category_id' => 7,
                'name' => 'Filete de Pescado Empanizado',
                'description' => null,
                'cost_price' => 51.00,
                'sale_price' => 128.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'category_id' => 7,
                'name' => 'Nugget de Pollo',
                'description' => null,
                'cost_price' => 58.00,
                'sale_price' => 145.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =============================================
            // EXTRAS (category_id: 8)
            // =============================================
            [
                'id' => 51,
                'category_id' => 8,
                'name' => 'Cama de Tostitos',
                'description' => 'Agrega una cama de tostitos a cualquier aguachile o ceviche.',
                'cost_price' => 10.00,
                'sale_price' => 25.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'category_id' => 8,
                'name' => 'Loba del Mar',
                'description' => 'Convierte cualquiera de nuestros platillos en loba del mar. 3kg de producto.',
                'cost_price' => 394.00,
                'sale_price' => 985.00,
                'is_available' => true,
                'image_url' => null,
                'preparation_time' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
